get http://localhost:5025/api/remove?nodes=1,2,8,11,5,4,7,9,12&value=9



get http://localhost:5025/api/remove?nodes=53,12,5,27,4,6,37,30,38&value=12


get http://localhost:5025/api/remove?nodes=2,1,3&value=1